version: '3.7'

volumes:
  mysql_data:

services:
  daphne:
    restart : always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 
    ports:
      - "8000:8000" 
    env_file:
      - .envs
    volumes:
      - .:/home
    depends_on:
      - mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .envs
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    ports:
      - "6379:6379"
